version: '2'

services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    user: '104'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - vpcstack
    
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
      #- '/home/ubuntu/repos/grafana/zabbix_server.conf:/etc/zabbix/zabbix_server.conf'
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ZBX_ENABLE_SNMP_TRAPS=true ##variavel nova
    networks:
      - vpcstack
    depends_on:
      - postgres

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:6.2-ubuntu-latest
    restart: always
    ports:
      - '8010:8080'
      - '443:8443'
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PHP_TZ=America/Sao_Paulo
    networks:
      - vpcstack
    depends_on:
      - postgres

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.0-latest
    container_name: zabbix_agent
    restart: always
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"
    networks: 
      - vpcstack
    depends_on:
      - postgres
      - zabbix-server    

  postgres:
    image: postgis/postgis:13-3.1-alpine
    container_name: postgres_monitoring
    command: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      -  postgres_data:/var/lib/postgresql/data
      - .docker/init/postgres/init_db/1_init_db.sh:/docker-entrypoint-initdb.d/1_init_db.sh
    networks:
      - vpcstack

networks:
  vpcstack:

volumes:
  grafana-data:
  postgres_data: